joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_turret_base
  pid: {p: 1.0, i: 0.001, d: 0.1}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_camera_link
  pid: {p: 1.0, i: 0.001, d: 0.10}
